### ISSUE TITLE
code fails on arepo sims

### ISSUE THREAD

**Issue by dnarayanan** [dnarayanan/caesar#11]
this has only been tested on an idealized simulation, but we get:

```
/home/pg3552/anaconda3/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fubar.py:347: RuntimeWarning: divide by zero encountered in true_divide
  efres = int(obj.simulation.boxsize.d / mips.d)
Traceback (most recent call last):
  File "/home/pg3552/anaconda3/bin/caesar", line 11, in <module>
    load_entry_point('caesar==0.2b0', 'console_scripts', 'caesar')()
  File "/home/pg3552/anaconda3/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/command_line.py", line 78, in run
    run_caesar(args.input, var_dict)
  File "/home/pg3552/anaconda3/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/command_line.py", line 130, in run_caesar
    obj.member_search(**args)
  File "/home/pg3552/anaconda3/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/main.py", line 337, in member_search
    fubar_halo(self)
  File "/home/pg3552/anaconda3/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fubar_halo.py", line 50, in fubar_halo
    halos.MIS = get_mean_interparticle_separation(obj).d # also computes omega_baryon and related quantities
  File "/home/pg3552/anaconda3/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fubar.py", line 347, in get_mean_interparticle_separation
    efres = int(obj.simulation.boxsize.d / mips.d)
OverflowError: cannot convert float infinity to integer```

**Comment by dnarayanan** [comment]
no idea when this was solved, but defnitely caesar works on arepo now
