### ISSUE TITLE
Unyt_array does not have attribute 'to_octree'

### ISSUE THREAD

**Issue by kusmic** [dnarayanan/caesar#65]
```
yt : [INFO     ] 2022-02-28 12:47:40,006 Calculating time from 1.667e-01 to be 3.711e+16 seconds
yt : [INFO     ] 2022-02-28 12:47:40,008 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2022-02-28 12:47:40,197 Parameters: current_time              = 3.71136025935506e+16 s
yt : [INFO     ] 2022-02-28 12:47:40,197 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2022-02-28 12:47:40,197 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2022-02-28 12:47:40,198 Parameters: domain_right_edge         = [6000. 6000. 6000.]
yt : [INFO     ] 2022-02-28 12:47:40,198 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2022-02-28 12:47:40,198 Parameters: current_redshift          = 4.999988038637683
yt : [INFO     ] 2022-02-28 12:47:40,198 Parameters: omega_lambda              = 0.6911
yt : [INFO     ] 2022-02-28 12:47:40,198 Parameters: omega_matter              = 0.3089
yt : [INFO     ] 2022-02-28 12:47:40,199 Parameters: omega_radiation           = 0.0
yt : [INFO     ] 2022-02-28 12:47:40,199 Parameters: hubble_constant           = 0.6774
Generating md5 hash: 2776it [00:01, 2033.38it/s]                             
                                        
yt : [INFO     ] 2022-02-28 12:47:42,034 Allocating for 3.361e+07 particles
Loading particle index: 
100%|███████████████████████████████████████████████████████| 72/72 [00:00<00:00, 493.22it/s]
yt : [INFO     ] 2022-02-28 12:47:50,735 member_search() running on 8 cores
yt : [INFO     ] 2022-02-28 12:47:52,916 No black holes found, RAM=0.5382 GB
The particle types will be loaded:  ['PartType0', 'PartType4', 'PartType1']
yt : [INFO     ] 2022-02-28 12:47:52,960 Calculated Omega_Baryon=0.0486007 and 256^3 effective resolution
yt : [INFO     ] 2022-02-28 12:47:52,967 Using b=0.2 for halos
yt : [INFO     ] 2022-02-28 12:47:52,968 Running 3D FOF to get Halo IDs, LL=6.91889, RAM=0.4757 GB
Traceback (most recent call last):
  File "do_caesar.py", line 41, in <module>
    obj.member_search(haloid='fof', b_halo=0.2, dust=False, blackholes=False, nproc=8)
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/main.py", line 340, in member_search
    fubar_halo(self)
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fubar_halo.py", line 64, in fubar_halo
    halos.load_haloid()
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fof6d.py", line 48, in load_haloid
    self.run_caesar_fof(self.obj)
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fof6d.py", line 86, in run_caesar_fof
    haloid_all = fof(self.obj, pos, LL, group_type='halo')  # run FOF
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fubar.py", line 67, in fof
    ot  = pos.to_octree()
AttributeError: 'unyt_array' object has no attribute 'to_octree'
```
This is occuring when I try to run the `member_search()` method.
```
obj.member_search(haloid='fof', b_halo=0.2, dust=False, blackholes=False, nproc=8)
```

**Comment by dnarayanan** [comment]
thanks for filing this!   can you please confirm:

a. what sort of simulation is this (i.e. what is the base hydrocode)?

b. what hash of caesar are you on?

c. what is the yt version you're using (i.e.:

```
print(yt.__version__)
```

**Comment by kusmic** [comment]
yt version is 4.0.1. I am using a derivative of Gadget-3. Although, what is hash?

**Comment by dnarayanan** [comment]
ah okay - the first thing I'd do is update caesar.  there were some yt4.x compatibility issues that were fixed in august and later last year.  please let me know after updating if the error persists

**Comment by kusmic** [comment]
As of writing this, the process still seems to be going. It'll take a bit, but I think this issue is closed. Thank you!

**Comment by dnarayanan** [comment]
okay great - let me know if this (or anything else) comes up!

**Comment by kusmic** [comment]
It seems to work! Although, there is a deprecation warning from numpy, just as a heads-up.
```
/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/fof6d.py:98: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.haloid = np.asarray(self.haloid)
```
