### ISSUE TITLE
Cannot run caesar in v0.1 member search

### ISSUE THREAD

**Issue by kusmic** [dnarayanan/caesar#67]
Hello,

I have found an issue with the 6D FOF algorithm in v0.2 (I'll post in another issue thread to keep topics concise) and decide to run in v0.1 mode. However, I get this error output:
```
Traceback (most recent call last):
  File "do_caesar.py", line 39, in <module>
    obj.member_search(fof6d=True, fof6d_LL_factor=LL_pos, fof6d_mingrp=4, fof6d_velLL=LL_vel, nproc=8, v01_member_search=True)
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/main.py", line 334, in member_search
    self.data_manager._member_search_init()
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/data_manager.py", line 30, in _member_search_init
    self.load_particle_data(select=select)
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/data_manager.py", line 90, in load_particle_data
    pdata      = get_particles_for_FOF(self.obj, self.ptypes, select)
  File "/home/local/Anaconda3-2020.02/envs/py3samir/lib/python3.7/site-packages/caesar-0.2b0-py3.7-linux-x86_64.egg/caesar/property_manager.py", line 437, in get_particles_for_FOF
    if obj.load_haloid:
AttributeError: 'CAESAR' object has no attribute 'load_haloid'
```

**Comment by weiguangcui** [comment]
Hi @kusmic ,

May you show your do_caesar.py file? I am not sure about your obj is a CAESAR object or not.

**Comment by kusmic** [comment]
So the code is:

`
import yt
import caesar
import glob
import os
from scipy.spatial.distance import pdist
import numpy as np

model = "pl9n384"
simdir = f"/home/users/samirk/Research/{model}"

D = 200
a = D**(-1/3)
b = np.sqrt(D)

# Make directory if not exist
if not os.path.isdir("caesar_out"):
    os.system("mkdir caesar_out")

ni = 39
nf = 39

for i in range(ni,nf+1):
    snap = f"{simdir}/snapdir_{i:03}/snap_{model}_{i:03}.0.hdf5"
    bbox = [[0,9000.],[0,9000.],[0,9000.]]
    unit_base = {
        "length": (1.0, "kpccm/h"),
        "velocity": (1.0, "km/s/(a**(1/2))"),
        "mass": (1e10, "Msun/h"),
    }

    ds = yt.load(snap, unit_base=unit_base, bounding_box=bbox)

    ad = ds.all_data()
    gasPos = ad[ds.fields.PartType0.Coordinates].value[:100]
    pdist_pos = pdist(gasPos)
    mean_part_sep = np.mean(pdist_pos)
    LL_pos = 0.04 * mean_part_sep
    del pdist_pos
    LL_vel = np.sqrt(D)
    print(LL_pos)

    obj = caesar.CAESAR(ds)

    # So here is the bulk snapshot analyzer it seems
    obj.member_search(haloid="fof", unbind_halos=True, unbind_galaxies=True, fof6d=True, fof6d_LL_factor=LL_pos, fof6d_mingrp=4, fof6d_velLL=LL_vel, nproc=1)#, v01_member_search=True)

    # Now trying progenitor stuff


    caesarfile = f"caesar_out/caesar_FOF6D_{i:03}.hdf5"
    obj.save(caesarfile)
    del ds, obj

print("Done.")
`

**Comment by weiguangcui** [comment]
This obj is not a halo object. Please refer to the fubar_halo() function for detailed procedures.
