### ISSUE TITLE
Error Compiling Cython file while Installing Caesar Package

### ISSUE THREAD

**Issue by h33rman** [dnarayanan/caesar#88]
I have been trying to install the Caesar package, but I'm encountering a Cython compilation error.

Here are the steps I've taken:

I activated my conda environment, I tried with base and myenv
I tried to run python setup.py install in the Caesar package directory.
However, the installation fails with the error below 

**Environment:**

OS: Ubuntu 20.04
Python version: 3.11 (from Anaconda)
Cython version: ( 3.0.0           py311h5eee18b_0)

**Additional Context:**
I have installed all the dependencies according to the package's installation instructions, and I am still encountering this issue. I have also tried updating Cython, but the issue persists.

**OUTPUT**
(base) herman@ThinkPad:~/Downloads/caesar-master$ sudo python3 setup.py install
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing caesar.egg-info/PKG-INFO
writing dependency_links to caesar.egg-info/dependency_links.txt
writing entry points to caesar.egg-info/entry_points.txt
writing requirements to caesar.egg-info/requires.txt
writing top-level names to caesar.egg-info/top_level.txt
reading manifest file 'caesar.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'caesar.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Compiling caesar/group_funcs/group_funcs.pyx because it changed.
[1/1] Cythonizing caesar/group_funcs/group_funcs.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef part_struct *grp_partinfo

    # get radius of each particle, sort by radii
    grp_partinfo = <part_struct *> malloc((nparticles)*sizeof(part_struct))  # allocate particle info
    nogil_load_partinfo(mass, pos, vel, ptype, cent_pos, cent_vel, grp_partinfo, Lbox, istart, iend, ndim)
    qsort(<void*>grp_partinfo, <size_t>(nparticles), sizeof(part_struct), mycmp)
                                                                          ^
------------------------------------------------------------

caesar/group_funcs/group_funcs.pyx:404:74: Cannot assign type 'int (const_void *, const_void *) except? -1 nogil' to 'int (*)(const_void *, const_void *) noexcept'
Traceback (most recent call last):
  File "/home/herman/Downloads/caesar-master/setup.py", line 69, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.10/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
    new_ext = cythonize(
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: caesar/group_funcs/group_funcs.pyx

**Comment by weiguangcui** [comment]
I think this may be caused by Cython, your version is much higher. Actually, I never see the cython in 3.0. I am currently using `Cython version 0.29.21`. May you give this version a try?

**Comment by her7man** [comment]
I didn't know why  I get this version of cython 3.0, 
But by following your advice, I switched to Cython version 0.29.21 and it resolved the issue I was facing. I really appreciate the time you took to guide me through this, and your expertise was invaluable.

Thanks once again for your assistance!
