### ISSUE TITLE
Compilation error in build

### ISSUE THREAD

**Issue by kyleaoman** [dnarayanan/caesar#97]
My daily CI tests for swiftgalaxy failed this morning with an error building caesar. Yesterday's build passed and neither caesar nor swiftgalaxy have any commits in the past day, so I expect that this is some kind of version conflict with a caesar dependency or similar. However, it crashes with a Cython compiler error that looks like it could be due to an actual bug in the caesar code (?):

```
2023-10-18T03:26:37.0550792Z       
2023-10-18T03:26:37.0551088Z       Error compiling Cython file:
2023-10-18T03:26:37.0551620Z       ------------------------------------------------------------
2023-10-18T03:26:37.0552068Z       ...
2023-10-18T03:26:37.0552327Z       
2023-10-18T03:26:37.0552697Z           # reset order to order of galaxies in caesar file
2023-10-18T03:26:37.0553220Z           gmass = np.array(galaxy_mass)
2023-10-18T03:26:37.0553676Z           for ipt in range(len(quants)):
2023-10-18T03:26:37.0554151Z               for ih,ig in enumerate(g_indexes):
2023-10-18T03:26:37.0554670Z                   galaxy_mass[ipt,ig] = gmass[ipt,ih]
2023-10-18T03:26:37.0555131Z                              ^
2023-10-18T03:26:37.0555726Z       ------------------------------------------------------------
2023-10-18T03:26:37.0556180Z       
2023-10-18T03:26:37.0556842Z       caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx:929:23: Compiler crash in AnalyseExpressionsTransform
```

And with more context:

```
2023-10-18T03:26:06.0196686Z Building wheels for collected packages: caesar, progress, future
2023-10-18T03:26:06.0207691Z   Building wheel for caesar (pyproject.toml): started
2023-10-18T03:26:37.0100707Z   Building wheel for caesar (pyproject.toml): finished with status 'error'
2023-10-18T03:26:37.0335413Z   error: subprocess-exited-with-error
2023-10-18T03:26:37.0336123Z   
2023-10-18T03:26:37.0337343Z   × Building wheel for caesar (pyproject.toml) did not run successfully.
2023-10-18T03:26:37.0338052Z   │ exit code: 1
2023-10-18T03:26:37.0338440Z   ╰─> [238 lines of output]
2023-10-18T03:26:37.0338810Z       running bdist_wheel
2023-10-18T03:26:37.0339151Z       running build
2023-10-18T03:26:37.0339467Z       running build_py
2023-10-18T03:26:37.0339790Z       creating build
2023-10-18T03:26:37.0340233Z       creating build/lib.linux-x86_64-cpython-39
2023-10-18T03:26:37.0340848Z       creating build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0341643Z       copying caesar/zoom_funcs.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0342544Z       copying caesar/fof6d.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0343412Z       copying caesar/assignment.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0344291Z       copying caesar/loader.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0345147Z       copying caesar/fubar_halo.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0346021Z       copying caesar/linking.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0346892Z       copying caesar/progen_rad.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0347745Z       copying caesar/fubar.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0348607Z       copying caesar/old_loader.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0349446Z       copying caesar/main.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0350318Z       copying caesar/treecool_data.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0351184Z       copying caesar/saver.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0352010Z       copying caesar/utils.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0352905Z       copying caesar/property_manager.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0353808Z       copying caesar/__init__.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0354658Z       copying caesar/driver.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0355511Z       copying caesar/__version__.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0356414Z       copying caesar/command_line.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0357289Z       copying caesar/progen.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0358161Z       copying caesar/data_manager.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0359428Z       copying caesar/simulation_attributes.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0360417Z       copying caesar/particle_list.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0361457Z       copying caesar/vtk_funcs.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0362311Z       copying caesar/group.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0363206Z       copying caesar/periodic_kdtree.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0369593Z       copying caesar/vtk_vis.py -> build/lib.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0370404Z       creating build/lib.linux-x86_64-cpython-39/caesar/pyloser
2023-10-18T03:26:37.0371322Z       copying caesar/pyloser/atten_laws.py -> build/lib.linux-x86_64-cpython-39/caesar/pyloser
2023-10-18T03:26:37.0372375Z       copying caesar/pyloser/__init__.py -> build/lib.linux-x86_64-cpython-39/caesar/pyloser
2023-10-18T03:26:37.0373440Z       copying caesar/pyloser/pyloser.py -> build/lib.linux-x86_64-cpython-39/caesar/pyloser
2023-10-18T03:26:37.0374134Z       running build_ext
2023-10-18T03:26:37.0375303Z       performance hint: caesar/group_funcs/group_funcs.pyx:62:5: Exception check on 'nogil_CoM_quants' will always require the GIL to be acquired.
2023-10-18T03:26:37.0376522Z       Possible solutions:
2023-10-18T03:26:37.0377528Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0378802Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0380194Z       performance hint: caesar/group_funcs/group_funcs.pyx:116:5: Exception check on 'nogil_load_partinfo' will always require the GIL to be acquired.
2023-10-18T03:26:37.0381190Z       Possible solutions:
2023-10-18T03:26:37.0382171Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0384008Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0385398Z       performance hint: caesar/group_funcs/group_funcs.pyx:224:5: Exception check on 'nogil_angular_quants' will always require the GIL to be acquired.
2023-10-18T03:26:37.0386404Z       Possible solutions:
2023-10-18T03:26:37.0387393Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0388648Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0390135Z       performance hint: caesar/group_funcs/group_funcs.pyx:329:5: Exception check on 'nogil_virial_quants' will always require the GIL to be acquired.
2023-10-18T03:26:37.0391123Z       Possible solutions:
2023-10-18T03:26:37.0392108Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0393359Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0394692Z       performance hint: caesar/group_funcs/group_funcs.pyx:360:5: Exception check on 'nogil_rotator' will always require the GIL to be acquired.
2023-10-18T03:26:37.0395653Z       Possible solutions:
2023-10-18T03:26:37.0396641Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0397882Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0399242Z       performance hint: caesar/group_funcs/group_funcs.pyx:395:5: Exception check on 'nogil_radial_quants' will always require the GIL to be acquired.
2023-10-18T03:26:37.0400231Z       Possible solutions:
2023-10-18T03:26:37.0401482Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0402740Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0403875Z       performance hint: caesar/group_funcs/group_funcs.pyx:284:17: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0404756Z       Possible solutions:
2023-10-18T03:26:37.0405729Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0406975Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0408104Z       performance hint: caesar/group_funcs/group_funcs.pyx:404:23: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0408982Z       Possible solutions:
2023-10-18T03:26:37.0409974Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0411229Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0412449Z       performance hint: caesar/group_funcs/group_funcs.pyx:429:28: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0413322Z       Possible solutions:
2023-10-18T03:26:37.0414297Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0415532Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0416660Z       performance hint: caesar/group_funcs/group_funcs.pyx:433:27: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0417521Z       Possible solutions:
2023-10-18T03:26:37.0418493Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0419735Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0420854Z       performance hint: caesar/group_funcs/group_funcs.pyx:783:24: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0421725Z       Possible solutions:
2023-10-18T03:26:37.0422737Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0423970Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0425099Z       performance hint: caesar/group_funcs/group_funcs.pyx:787:31: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0466131Z       Possible solutions:
2023-10-18T03:26:37.0467154Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0468393Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0469514Z       performance hint: caesar/group_funcs/group_funcs.pyx:789:31: Exception check will always require the GIL to be acquired.
2023-10-18T03:26:37.0470391Z       Possible solutions:
2023-10-18T03:26:37.0471366Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0472605Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0473431Z       Compiling caesar/group_funcs/group_funcs.pyx because it changed.
2023-10-18T03:26:37.0474111Z       [1/1] Cythonizing caesar/group_funcs/group_funcs.pyx
2023-10-18T03:26:37.0474720Z       building 'caesar.group_funcs' extension
2023-10-18T03:26:37.0475299Z       creating build/temp.linux-x86_64-cpython-39
2023-10-18T03:26:37.0476055Z       creating build/temp.linux-x86_64-cpython-39/caesar
2023-10-18T03:26:37.0522770Z       creating build/temp.linux-x86_64-cpython-39/caesar/group_funcs
2023-10-18T03:26:37.0525388Z       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/hostedtoolcache/Python/3.9.18/x64/include/python3.9 -I/tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/numpy/core/include -c caesar/group_funcs/group_funcs.c -o build/temp.linux-x86_64-cpython-39/caesar/group_funcs/group_funcs.o -fopenmp
2023-10-18T03:26:37.0528310Z       In file included from /tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
2023-10-18T03:26:37.0529895Z                        from /tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
2023-10-18T03:26:37.0531354Z                        from /tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
2023-10-18T03:26:37.0532320Z                        from caesar/group_funcs/group_funcs.c:1200:
2023-10-18T03:26:37.0534211Z       /tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
2023-10-18T03:26:37.0536155Z          17 | #warning "Using deprecated NumPy API, disable it with " \
2023-10-18T03:26:37.0536707Z             |  ^~~~~~~
2023-10-18T03:26:37.0538997Z       gcc -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.9.18/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.9.18/x64/lib build/temp.linux-x86_64-cpython-39/caesar/group_funcs/group_funcs.o -L/opt/hostedtoolcache/Python/3.9.18/x64/lib -o build/lib.linux-x86_64-cpython-39/caesar/group_funcs.cpython-39-x86_64-linux-gnu.so -fopenmp
2023-10-18T03:26:37.0541939Z       performance hint: caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx:448:5: Exception check on '_get_galaxy_hydrogen_masses' will always require the GIL to be acquired.
2023-10-18T03:26:37.0543054Z       Possible solutions:
2023-10-18T03:26:37.0544053Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0545336Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0546839Z       performance hint: caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx:1142:5: Exception check on 'get_galaxy_aperture_masses' will always require the GIL to be acquired.
2023-10-18T03:26:37.0547950Z       Possible solutions:
2023-10-18T03:26:37.0548933Z           1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2023-10-18T03:26:37.0550163Z           2. Use an 'int' return type on the function to allow an error code to be returned.
2023-10-18T03:26:37.0550792Z       
2023-10-18T03:26:37.0551088Z       Error compiling Cython file:
2023-10-18T03:26:37.0551620Z       ------------------------------------------------------------
2023-10-18T03:26:37.0552068Z       ...
2023-10-18T03:26:37.0552327Z       
2023-10-18T03:26:37.0552697Z           # reset order to order of galaxies in caesar file
2023-10-18T03:26:37.0553220Z           gmass = np.array(galaxy_mass)
2023-10-18T03:26:37.0553676Z           for ipt in range(len(quants)):
2023-10-18T03:26:37.0554151Z               for ih,ig in enumerate(g_indexes):
2023-10-18T03:26:37.0554670Z                   galaxy_mass[ipt,ig] = gmass[ipt,ih]
2023-10-18T03:26:37.0555131Z                              ^
2023-10-18T03:26:37.0555726Z       ------------------------------------------------------------
2023-10-18T03:26:37.0556180Z       
2023-10-18T03:26:37.0556842Z       caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx:929:23: Compiler crash in AnalyseExpressionsTransform
2023-10-18T03:26:37.0557606Z       
2023-10-18T03:26:37.0558132Z       ModuleNode.body = StatListNode(hydrogen_mass_calc.pyx:1:0)
2023-10-18T03:26:37.0558872Z       StatListNode.stats[23] = StatListNode(hydrogen_mass_calc.pyx:761:0)
2023-10-18T03:26:37.0559704Z       StatListNode.stats[0] = CompilerDirectivesNode(hydrogen_mass_calc.pyx:761:0)
2023-10-18T03:26:37.0560708Z       CompilerDirectivesNode.body = StatListNode(hydrogen_mass_calc.pyx:761:0)
2023-10-18T03:26:37.0561504Z       StatListNode.stats[0] = DefNode(hydrogen_mass_calc.pyx:761:0,
2023-10-18T03:26:37.0562171Z           defaults_struct = '__pyx_defaults',
2023-10-18T03:26:37.0562920Z           doc = ' Compute aperture masses in various quantities; standalone version ',
2023-10-18T03:26:37.0563578Z           is_cyfunction = True,
2023-10-18T03:26:37.0563972Z           modifiers = [...]/0,
2023-10-18T03:26:37.0564415Z           name = 'get_aperture_masses',
2023-10-18T03:26:37.0564853Z           np_args_idx = [...]/0,
2023-10-18T03:26:37.0565232Z           num_required_args = 3,
2023-10-18T03:26:37.0565629Z           outer_attrs = [...]/2,
2023-10-18T03:26:37.0566048Z           py_wrapper_required = True,
2023-10-18T03:26:37.0566518Z           reqd_kw_flags_cname = '0',
2023-10-18T03:26:37.0566916Z           used = True)
2023-10-18T03:26:37.0567760Z       File 'Nodes.py', line 397, in analyse_expressions: StatListNode(hydrogen_mass_calc.pyx:765:4,
2023-10-18T03:26:37.0568486Z           is_terminator = True)
2023-10-18T03:26:37.0569252Z       File 'Nodes.py', line 397, in analyse_expressions: StatListNode(hydrogen_mass_calc.pyx:927:4)
2023-10-18T03:26:37.0570343Z       File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(hydrogen_mass_calc.pyx:927:4)
2023-10-18T03:26:37.0571450Z       File 'Nodes.py', line 397, in analyse_expressions: StatListNode(hydrogen_mass_calc.pyx:928:8)
2023-10-18T03:26:37.0572537Z       File 'Nodes.py', line 7556, in analyse_expressions: ForInStatNode(hydrogen_mass_calc.pyx:928:8)
2023-10-18T03:26:37.0573636Z       File 'Nodes.py', line 397, in analyse_expressions: StatListNode(hydrogen_mass_calc.pyx:929:39)
2023-10-18T03:26:37.0574816Z       File 'Nodes.py', line 6026, in analyse_expressions: SingleAssignmentNode(hydrogen_mass_calc.pyx:929:39)
2023-10-18T03:26:37.0575994Z       File 'Nodes.py', line 6164, in analyse_types: SingleAssignmentNode(hydrogen_mass_calc.pyx:929:39)
2023-10-18T03:26:37.0577140Z       File 'ExprNodes.py', line 4085, in analyse_target_types: IndexNode(hydrogen_mass_calc.pyx:929:23,
2023-10-18T03:26:37.0577875Z           is_subscript = True,
2023-10-18T03:26:37.0578260Z           result_is_used = True,
2023-10-18T03:26:37.0578647Z           use_managed_ref = True)
2023-10-18T03:26:37.0579497Z       File 'ExprNodes.py', line 4123, in analyse_base_and_index_types: IndexNode(hydrogen_mass_calc.pyx:929:23,
2023-10-18T03:26:37.0580274Z           is_subscript = True,
2023-10-18T03:26:37.0580655Z           result_is_used = True,
2023-10-18T03:26:37.0581044Z           use_managed_ref = True)
2023-10-18T03:26:37.0581872Z       File 'ExprNodes.py', line 4349, in analyse_as_buffer_operation: IndexNode(hydrogen_mass_calc.pyx:929:23,
2023-10-18T03:26:37.0582635Z           is_subscript = True,
2023-10-18T03:26:37.0583012Z           result_is_used = True,
2023-10-18T03:26:37.0583399Z           use_managed_ref = True)
2023-10-18T03:26:37.0584227Z       File 'ExprNodes.py', line 4968, in analyse_types: MemoryViewIndexNode(hydrogen_mass_calc.pyx:929:23,
2023-10-18T03:26:37.0584995Z           is_memview_index = True,
2023-10-18T03:26:37.0585384Z           memslice_index = True,
2023-10-18T03:26:37.0585768Z           result_is_used = True,
2023-10-18T03:26:37.0586148Z           use_managed_ref = True,
2023-10-18T03:26:37.0586535Z           writable_needed = True)
2023-10-18T03:26:37.0586887Z       
2023-10-18T03:26:37.0587224Z       Compiler crash traceback from this point on:
2023-10-18T03:26:37.0599871Z         File "/tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 4968, in analyse_types
2023-10-18T03:26:37.0601906Z           performance_hint(index.pos, "Index should be typed for more efficient access")
2023-10-18T03:26:37.0602965Z       TypeError: performance_hint() missing 1 required positional argument: 'env'
2023-10-18T03:26:37.0603853Z       Compiling caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx because it changed.
2023-10-18T03:26:37.0604694Z       [1/1] Cythonizing caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx
2023-10-18T03:26:37.0605316Z       Traceback (most recent call last):
2023-10-18T03:26:37.0606639Z         File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2023-10-18T03:26:37.0607706Z           main()
2023-10-18T03:26:37.0608818Z         File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2023-10-18T03:26:37.0610036Z           json_out['return_val'] = hook(**hook_input['kwargs'])
2023-10-18T03:26:37.0611392Z         File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
2023-10-18T03:26:37.0612674Z           return _build_backend().build_wheel(wheel_directory, config_settings,
2023-10-18T03:26:37.0614060Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
2023-10-18T03:26:37.0615037Z           return self._build_with_temp_dir(
2023-10-18T03:26:37.0616194Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
2023-10-18T03:26:37.0617182Z           self.run_setup()
2023-10-18T03:26:37.0618158Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
2023-10-18T03:26:37.0619283Z           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
2023-10-18T03:26:37.0620543Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
2023-10-18T03:26:37.0621466Z           exec(code, locals())
2023-10-18T03:26:37.0621924Z         File "<string>", line 69, in <module>
2023-10-18T03:26:37.0623009Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
2023-10-18T03:26:37.0623940Z           return distutils.core.setup(**attrs)
2023-10-18T03:26:37.0625035Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
2023-10-18T03:26:37.0625966Z           return run_commands(dist)
2023-10-18T03:26:37.0627046Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
2023-10-18T03:26:37.0627987Z           dist.run_commands()
2023-10-18T03:26:37.0629043Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
2023-10-18T03:26:37.0629989Z           self.run_command(cmd)
2023-10-18T03:26:37.0630986Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
2023-10-18T03:26:37.0631896Z           super().run_command(command)
2023-10-18T03:26:37.0632982Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-10-18T03:26:37.0633917Z           cmd_obj.run()
2023-10-18T03:26:37.0634800Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
2023-10-18T03:26:37.0635653Z           self.run_command("build")
2023-10-18T03:26:37.0636705Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
2023-10-18T03:26:37.0637701Z           self.distribution.run_command(command)
2023-10-18T03:26:37.0638854Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
2023-10-18T03:26:37.0639745Z           super().run_command(command)
2023-10-18T03:26:37.0640965Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-10-18T03:26:37.0642005Z           cmd_obj.run()
2023-10-18T03:26:37.0643037Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
2023-10-18T03:26:37.0644008Z           self.run_command(cmd_name)
2023-10-18T03:26:37.0645083Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
2023-10-18T03:26:37.0646073Z           self.distribution.run_command(command)
2023-10-18T03:26:37.0647131Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
2023-10-18T03:26:37.0648044Z           super().run_command(command)
2023-10-18T03:26:37.0649125Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-10-18T03:26:37.0650170Z           cmd_obj.run()
2023-10-18T03:26:37.0651128Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
2023-10-18T03:26:37.0652038Z           _build_ext.run(self)
2023-10-18T03:26:37.0653102Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
2023-10-18T03:26:37.0654086Z           self.build_extensions()
2023-10-18T03:26:37.0655260Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
2023-10-18T03:26:37.0656340Z           self._build_extensions_serial()
2023-10-18T03:26:37.0657630Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
2023-10-18T03:26:37.0658737Z           self.build_extension(ext)
2023-10-18T03:26:37.0659865Z         File "/tmp/pip-build-env-7wnhqbws/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
2023-10-18T03:26:37.0660902Z           _build_ext.build_extension(self, ext)
2023-10-18T03:26:37.0662057Z         File "/tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
2023-10-18T03:26:37.0663037Z           new_ext = cythonize(
2023-10-18T03:26:37.0664072Z         File "/tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
2023-10-18T03:26:37.0665013Z           cythonize_one(*args)
2023-10-18T03:26:37.0666077Z         File "/tmp/pip-build-env-7wnhqbws/normal/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
2023-10-18T03:26:37.0667114Z           raise CompileError(None, pyx_file)
2023-10-18T03:26:37.0667872Z       Cython.Compiler.Errors.CompileError: caesar/hydrogen_mass_calc/hydrogen_mass_calc.pyx
2023-10-18T03:26:37.0668589Z       [end of output]
2023-10-18T03:26:37.0668894Z   
2023-10-18T03:26:37.0669429Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2023-10-18T03:26:37.0670174Z   ERROR: Failed building wheel for caesar
```

**Comment by saethlin** [comment]
That looks like a Cython bug. There are a lot of warnings, but that looks like a compiler crash which is always a bug in the compiler. There was also a new Cython version yesterday.
